export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ACTIVITIES_REQUEST = 'ACTIVITIES_REQUEST';
export const ACTIVITIES_SUCCESS = 'ACTIVITIES_SUCCESS';
export const ACTIVITIES_ERROR = 'ACTIVITIES_ERROR';

export const ACTIVITY_REQUEST = 'ACTIVITY_REQUEST';
export const ACTIVITY_SUCCESS = 'ACTIVITY_SUCCESS';
export const ACTIVITY_ERROR = 'ACTIVITY_ERROR';

export const ORGANIZATIONS_REQUEST = 'ORGANIZATIONS_REQUEST';
export const ORGANIZATIONS_SUCCESS = 'ORGANIZATIONS_SUCCESS';
export const ORGANIZATIONS_ERROR = 'ORGANIZATIONS_ERROR';

export const ORGANIZATION_REQUEST = 'ORGANIZATION_REQUEST';
export const ORGANIZATION_SUCCESS = 'ORGANIZATION_SUCCESS';
export const ORGANIZATION_ERROR = 'ORGANIZATION_ERROR';